[install.scopes]
"@willebrew" = { token = "$GITHUB_TOKEN", url = "https://npm.pkg.github.com/" }

[test]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "/dist/",
  "\\/dist\\/",
  "\\/\\.next\\/",
  "\\/coverage\\/",
  "\\/\\.turbo\\/",
  "\\/node_modules\\/",
  "\\/Documents\\/",
]
