[install.scopes]
"@willebrew" = { token = "$GITHUB_TOKEN", url = "https://npm.pkg.github.com/" }

[test]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "dist",
  "\\.next",
  "node_modules",
  "coverage",
  "\\.turbo",
  "Documents",
]
